(()=>{'use strict';
const $=id=>document.getElementById(id), parse=v=>Number(String(v??'').trim().replace(',','.')), euro=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(v);
const defaults={electricityPrice:.41,fuelPrice:1.90,electricConsumption:23,fuelConsumption:8.7,hybridElectric:11.5,hybridFuel:3.8,chargingLoss:10,annualDistance:15000};
const fields=Object.keys(defaults); let state={...defaults,...loadJSON('glc-v61-values',{})};
function loadJSON(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}} function saveJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
function fill(){fields.forEach(k=>$(k).value=String(state[k]).replace('.',','));$('tankApiKey').value=localStorage.getItem('glc-tanker-key')||'';$('shortcutName').value=localStorage.getItem('glc-mobility-shortcut')||'mobility+ öffnen';const mb=loadJSON('glc-mb-config',{});$('mbEndpoint').value=mb.endpoint||'';$('mbToken').value=mb.token||''}
function calculate(){const v={};fields.forEach(k=>v[k]=parse($(k).value));if(Object.values(v).some(n=>!Number.isFinite(n)||n<0)||!v.electricConsumption||!v.fuelConsumption||!v.annualDistance){$('error').hidden=false;$('error').textContent='Bitte alle Werte vollständig und gültig eingeben.';return}$('error').hidden=true;const loss=1+v.chargingLoss/100;const c={electric:v.electricConsumption*loss*v.electricityPrice,hybrid:v.hybridElectric*loss*v.electricityPrice+v.hybridFuel*v.fuelPrice,fuel:v.fuelConsumption*v.fuelPrice};const labels={electric:'Elektrisch',hybrid:'Hybrid',fuel:'Benzin'},icons={electric:'⚡',hybrid:'⚡⛽',fuel:'⛽'};const sorted=Object.entries(c).sort((a,b)=>a[1]-b[1]);const best=sorted[0],second=sorted[1];$('bestMode').textContent=labels[best[0]]+' fahren';$('bestBadge').textContent=labels[best[0]];$('modeIcon').textContent=icons[best[0]];$('bestText').textContent=`Spart ${euro(second[1]-best[1])} je 100 km gegenüber Platz 2.`;$('ranking').innerHTML=sorted.map(([k,val],i)=>`<div><b>${i+1}. ${labels[k]}</b><span>${euro(val)} / 100 km</span></div>`).join('');['electric','hybrid','fuel'].forEach(k=>{$(k+'Cost').textContent=euro(c[k]);$(k+'Year').textContent=euro(c[k]*v.annualDistance/100)+' pro Jahr';document.querySelector(`[data-mode="${k}"]`).classList.toggle('best',k===best[0])});state=v;saveJSON('glc-v61-values',v)}
$('calcForm').addEventListener('submit',e=>{e.preventDefault();calculate()});$('resetBtn').onclick=()=>{state={...defaults};fill();calculate()};
$('mapsBtn').onclick=()=>location.href='https://www.google.com/maps/search/?api=1&query=Tankstelle';
function runShortcut(){const name=$('shortcutName').value.trim();if(!name){alert('Bitte zuerst den exakten Namen deines Kurzbefehls eintragen.');return}location.href='shortcuts://run-shortcut?name='+encodeURIComponent(name)}$('mobilityBtn').onclick=runShortcut;$('testShortcutBtn').onclick=runShortcut;$('saveShortcutBtn').onclick=()=>{localStorage.setItem('glc-mobility-shortcut',$('shortcutName').value.trim());alert('Kurzbefehl gespeichert.')};
$('mercedesAppBtn').onclick=()=>location.href='https://me.secure.mercedes-benz.com/';
$('tankSaveBtn').onclick=()=>{localStorage.setItem('glc-tanker-key',$('tankApiKey').value.trim());$('tankStatus').textContent='Key gespeichert'};
$('tankLoadBtn').onclick=()=>{const key=$('tankApiKey').value.trim();const radius=Math.min(25,Math.max(1,parse($('tankRadius').value)||5));if(!key)return alert('Bitte deinen Tankerkönig API-Key eingeben.');if(!navigator.geolocation)return alert('Standort wird von diesem Browser nicht unterstützt.');$('tankStatus').textContent='Standort wird ermittelt…';navigator.geolocation.getCurrentPosition(async p=>{try{const u=new URL('https://creativecommons.tankerkoenig.de/json/list.php');u.search=new URLSearchParams({lat:p.coords.latitude,lng:p.coords.longitude,rad:radius,sort:'price',type:'e10',apikey:key});const r=await fetch(u);const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'API-Abfrage fehlgeschlagen');const open=(d.stations||[]).filter(s=>s.isOpen&&typeof s.price==='number');if(!open.length)throw new Error('Keine geöffnete E10-Tankstelle mit Preis gefunden.');const cheapest=open[0];$('fuelPrice').value=String(cheapest.price).replace('.',',');calculate();$('tankStatus').textContent=`${euro(cheapest.price)}/l übernommen`;$('stations').innerHTML=open.slice(0,5).map(s=>`<article><b>${s.name}</b><span>${euro(s.price)}/l · ${Number(s.dist).toLocaleString('de-DE')} km</span><small>${s.street} ${s.houseNumber}, ${s.place}</small></article>`).join('');localStorage.setItem('glc-tanker-key',key)}catch(e){$('tankStatus').textContent='Fehler';$('stations').innerHTML=`<p class="error">${e.message}. Falls der Browser die direkte API-Abfrage blockiert, ist ein kleiner CORS-Proxy/Backend-Endpunkt nötig.</p>`}},e=>{$('tankStatus').textContent='Standort verweigert';alert('Bitte Standortzugriff erlauben.')},{enableHighAccuracy:true,timeout:12000})};
$('saveMbBtn').onclick=()=>{saveJSON('glc-mb-config',{endpoint:$('mbEndpoint').value.trim(),token:$('mbToken').value.trim()});$('mbStatus').textContent='Connector gespeichert'};
$('loadMbBtn').onclick=async()=>{const endpoint=$('mbEndpoint').value.trim(),token=$('mbToken').value.trim();if(!endpoint)return alert('Bitte einen echten Backend-Endpunkt eintragen.');$('mbStatus').textContent='Lädt…';try{const r=await fetch(endpoint,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();const pick=(...ks)=>ks.map(k=>d[k]).find(v=>v!==undefined&&v!==null);const mileage=pick('mileage','odometer','kilometerstand'),fuel=pick('fuelLevel','fuel','tank'),battery=pick('batteryLevel','stateOfCharge','soc'),range=pick('electricRange','rangeElectric','evRange'),ec=pick('electricConsumption','avgElectricConsumption'),fc=pick('fuelConsumption','avgFuelConsumption');$('mbMileage').textContent=mileage!=null?`${mileage} km`:'–';$('mbFuel').textContent=fuel!=null?`${fuel} %`:'–';$('mbBattery').textContent=battery!=null?`${battery} %`:'–';$('mbRange').textContent=range!=null?`${range} km`:'–';$('mbElecCons').textContent=ec!=null?`${ec} kWh/100 km`:'–';$('mbFuelCons').textContent=fc!=null?`${fc} l/100 km`:'–';if(ec!=null)$('electricConsumption').value=String(ec).replace('.',',');if(fc!=null)$('fuelConsumption').value=String(fc).replace('.',',');calculate();$('mbStatus').textContent='Live-Daten geladen'}catch(e){$('mbStatus').textContent='Verbindung fehlgeschlagen';alert('Mercedes-Backend nicht erreichbar: '+e.message)}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));fill();calculate();})();
